- Demonstrate Number object methods (toString, toFixed, toPrecision)
- Add toLocaleString example for Indian currency formatting
- Include Math object constants (PI, E) and methods
- Add examples for rounding (round, ceil, floor)
- Implement random number generation with different range